name: Build FastGPU-P Releases

on:
  push:
    branches: [ '**' ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        build_config: [Release]
        platform: [x86, x64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Publish
      run: dotnet publish FastGPU-P.sln /p:PublishProfile=${{ matrix.platform }}-${{ matrix.build_config }}.pubxml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FastGPU-P-${{ matrix.platform }}
        path: ./FastGPU-P/bin/publish/${{ matrix.platform }}-${{ matrix.build_config }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download x86 Artifacts
      uses: actions/download-artifact@v4
      with:
        name: FastGPU-P-x86
        path: ./FastGPU-P-x86

    - name: Download x64 Artifacts
      uses: actions/download-artifact@v4
      with:
        name: FastGPU-P-x64
        path: ./FastGPU-P-x64

    - name: Zip Artifacts for Release
      run: |
        cd ./FastGPU-P-x86 && zip -r ../FastGPU-P-x86.zip . && cd ..
        cd ./FastGPU-P-x64 && zip -r ../FastGPU-P-x64.zip . && cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          FastGPU-P-x86.zip
          FastGPU-P-x64.zip
        generate_release_notes: true
